spring.application.name=project-manager-service

spring.datasource.url=jdbc:mysql://localhost:3306/project_manager?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# Hibernate ddl auto options:
# validate | update | create | create-drop | none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avnish20kid@gmail.com
spring.mail.password=wjtdsofvhmbzqjns
spring.mail.properties.mail.smtp.auth=true

secret_key=Z1J2YjV4c3R4enBwMmxrZnhkY2Znc2huajVreW1xYWtzamRzaGZkZ2hoamtsa29wdXl0cmV3cW==

logging.level.org.springframework.security=DEBUG