const Stage = [
  'TO_BE_PICKED',
  'GATHERING_REQUIREMENTS',
  'BLOCKED',
  'DEV_IN_PROGRESS',
  'DEV_COMPLETED',
  'CODE_REVIEW',
  'QA_READY',
  'QA_IN_PROGRESS',
  'QA_COMPLETED',
  'UAT_READY',
  'UAT_IN_PROGRESS',
  'UAT_COMPLETED',
  'DEPLOYMENT_READY',
  'DEPLOYMENT_COMPLETED'
];

export default Stage;